source "https://rubygems.org"
gem 'petfinder_cli_app'
require "pry"
require 'bundler'

git_source(:github) {|| "https://github.com/#{gem 'petfinder_cli_app'}" }

# Specify your gem's dependencies in petfinder_cli_app.gemspec
gemspec
